package org.example.entity;

import org.example.annotations.JdbcAutoGenerated;
import org.example.annotations.JdbcField;
import org.example.annotations.JdbcTable;

import java.util.Objects;

@JdbcTable(table = "clients")
public class Client extends Entity {

    @JdbcField(name = "first_name", type = "VARCHAR(50)")
    private String firstName;

    @JdbcField(name = "last_name", type = "VARCHAR(50)")
    private String lastName;

    @JdbcAutoGenerated
    @JdbcField(name = "id", type = "INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT")
    private long id;

    public Client(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public Client() {
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Client client = (Client) o;
        return Objects.equals(firstName, client.firstName) &&
                Objects.equals(lastName, client.lastName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, lastName);
    }

    @Override
    public String toString() {
        return "Client{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }
}
