package org.example.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.example.annotation.JdbcAutoGenerated;
import org.example.annotation.JdbcField;
import org.example.annotation.JdbcId;
import org.example.annotation.JdbcTable;

import java.util.Objects;

@JdbcTable("clients")
public class Client extends Entity{

    @JsonProperty("firstname")
    @JdbcField("first_name")
    private String firstName;

    @JsonProperty("lastname")
    @JdbcField("last_name")
    private String lastName;

    @JdbcAutoGenerated
    @JdbcField("id")
    @JdbcId
    private long id;

    public Client(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public Client() {
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Client client = (Client) o;
        return Objects.equals(firstName, client.firstName) &&
                Objects.equals(lastName, client.lastName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, lastName);
    }

    @Override
    public String toString() {
        return "Client{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }
}
