package org.example.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.example.annotation.*;

import java.util.Objects;

@JdbcTable("users")
public class User extends Entity{

    @JsonProperty("login")
    @JdbcField("login")
    @JdbcNotNull
    private String login;

    @JsonProperty("password")
    @JdbcField("password")
    @JdbcNotNull
    private String password;

    @JsonProperty("email")
    @JdbcField("email")
    @JdbcNotNull
    private String email;

    @JsonProperty("firstname")
    @JdbcField("first_name")
    private String firstName;

    @JsonProperty("lastname")
    @JdbcField("last_name")
    private String lastName;

    @JdbcAutoGenerated
    @JdbcField("user_id")
    @JdbcId
    private int id;

    public User() {
    }

    public User(String login, String password, String email) {
        this.login = login;
        this.password = password;
        this.email = email;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getLogin() {
        return login;
    }

    public String getPassword() {
        return password;
    }

    public String getEmail() {
        return email;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return login.equals(user.login) &&
                password.equals(user.password) &&
                email.equals(user.email) &&
                Objects.equals(firstName, user.firstName) &&
                Objects.equals(lastName, user.lastName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(login, password, email, firstName, lastName);
    }
}
